"""Registry interface."""

from __future__ import annotations

from typing import List, Optional, Protocol, runtime_checkable

from datum.models import DataPackage


@runtime_checkable
class Registry(Protocol):
    """Shared interface for local and remote registries."""

    def list(self, q: str = "") -> List[DataPackage]: ...
    def get(self, id: str, version: str) -> Optional[DataPackage]: ...
    def latest(self, id: str) -> Optional[DataPackage]: ...
    def publish(self, pkg: DataPackage, overwrite: bool = False) -> object: ...
    def unpublish(self, id: str, version: str) -> bool: ...
    def versions(self, id: str) -> List[str]: ...
    def suggest(self, id_part: str, n: int = 3) -> List[str]: ...
